/*

Copyright (c) 2010, Jonathan Wayne Parrott

Please see the license.txt file included with this source
distribution for more information.

*/

#ifndef __PHOENIXKEYS__
#define __PHOENIXKEYS__

#include "config.h"

namespace phoenix
{

    //! Mouse button definitions
    /*!
    	Defines mouse buttons for window events
    	\sa EventReceiver
    */
    enum MouseButton
    {
        PHK_MB_LEFT     =   0,
        PHK_MB_RIGHT	=   1,
        PHK_MB_MIDDLE   =   2
    };

    //! Keyboard key definitions
    /*!
    	Defines keyboard keys for window events.
    	\sa EventReceiver
    */
	enum Key
    {
		// cjren, printable keys, check glfw3.h for details.
        
        Key_SPACE				=GLFW_KEY_SPACE,
        Key_MINUS               ='-',
        Key_PLUS				='+',
        Key_0					='0',
        Key_1					='1',
        Key_2					='2',
        Key_3					='3',
        Key_4					='4',
        Key_5					='5',
        Key_6					='6',
        Key_7					='7',
        Key_8					='8',
        Key_9					='9',
		Key_SEMICOLON           =';',
        Key_EQUAL               ='=',
		Key_A					='A',
        Key_B					='B',
        Key_C					='C',
        Key_D					='D',
        Key_E					='E',
        Key_F					='F',
        Key_G					='G',
        Key_H					='H',
        Key_I					='I',
        Key_J					='J',
        Key_K					='K',
        Key_L					='L',
        Key_M					='M',
        Key_N					='N',
        Key_O					='O',
        Key_P					='P',
        Key_Q					='Q',
        Key_R					='R',
        Key_S					='S',
        Key_T					='T',
        Key_U					='U',
        Key_V					='V',
        Key_W					='W',
        Key_X					='X',
        Key_Y					='Y',
        Key_Z					='Z',
        Key_a					='a',
        Key_b					='b',
        Key_c					='c',
        Key_d					='d',
        Key_e					='e',
        Key_f					='f',
        Key_g					='g',
        Key_h					='h',
        Key_i					='i',
        Key_j					='j',
        Key_k					='k',
        Key_l					='l',
        Key_m					='m',
        Key_n					='n',
        Key_o					='o',
        Key_p					='p',
        Key_q					='q',
        Key_r					='r',
        Key_s					='s',
        Key_t					='t',
        Key_u					='u',
        Key_v					='v',
        Key_w					='w',
        Key_x					='x',
        Key_y					='y',
        Key_z					='z',
        Key_RIGHTBRACKET        ='[',
        Key_BACKSLASH           ='\\',
		Key_LEFTBRACKET         =']',	 

		Key_BACKTICK            ='`',
		Key_TILDE				='~',
		Key_BANG				='!',
        Key_QUOTE               ='\'',
		Key_PIPE				='|',
        
		// cjren, function keys, check glfw3.h for details.
		Key_ESC					=GLFW_KEY_ESCAPE,
        Key_ENTER				=GLFW_KEY_ENTER,
        Key_TAB					=GLFW_KEY_TAB,
        Key_BACKSPACE			=GLFW_KEY_BACKSPACE,
        Key_INSERT				=GLFW_KEY_INSERT,
        Key_DEL					=GLFW_KEY_DELETE,
        Key_RIGHT				=GLFW_KEY_RIGHT,
        Key_LEFT				=GLFW_KEY_LEFT,
        Key_DOWN				=GLFW_KEY_DOWN,
        Key_UP					=GLFW_KEY_UP,
        Key_PAGEUP				=GLFW_KEY_PAGE_UP,
        Key_PAGEDOWN			=GLFW_KEY_PAGE_DOWN,
        Key_HOME				=GLFW_KEY_HOME,
        Key_END					=GLFW_KEY_END,
        
		Key_F1					=GLFW_KEY_F1,
        Key_F2					=GLFW_KEY_F2,
        Key_F3					=GLFW_KEY_F3,
        Key_F4					=GLFW_KEY_F4,
        Key_F5					=GLFW_KEY_F5,
        Key_F6					=GLFW_KEY_F6,
        Key_F7					=GLFW_KEY_F7,
        Key_F8					=GLFW_KEY_F8,
        Key_F9					=GLFW_KEY_F9,
        Key_F10					=GLFW_KEY_F10,
        Key_F11					=GLFW_KEY_F11,
        Key_F12					=GLFW_KEY_F12,
        Key_F13					=GLFW_KEY_F13,
        Key_F14					=GLFW_KEY_F14,
        Key_F15					=GLFW_KEY_F15,
        Key_F16					=GLFW_KEY_F16,
        Key_F17					=GLFW_KEY_F17,
        Key_F18					=GLFW_KEY_F18,
        Key_F19					=GLFW_KEY_F19,
        Key_F20					=GLFW_KEY_F20,
        Key_F21					=GLFW_KEY_F21,
        Key_F22					=GLFW_KEY_F22,
        Key_F23					=GLFW_KEY_F23,
        Key_F24					=GLFW_KEY_F24,
        Key_F25					=GLFW_KEY_F25,
        
		Key_KP_0				=GLFW_KEY_KP_0,
        Key_KP_1				=GLFW_KEY_KP_1,
        Key_KP_2				=GLFW_KEY_KP_2,
        Key_KP_3				=GLFW_KEY_KP_3,
        Key_KP_4				=GLFW_KEY_KP_4,
        Key_KP_5				=GLFW_KEY_KP_5,
        Key_KP_6				=GLFW_KEY_KP_6,
        Key_KP_7				=GLFW_KEY_KP_7,
        Key_KP_8				=GLFW_KEY_KP_8,
        Key_KP_9				=GLFW_KEY_KP_9, 
        Key_KP_DECIMAL			=GLFW_KEY_KP_DECIMAL,
        Key_KP_DIVIDE			=GLFW_KEY_KP_DIVIDE,
        Key_KP_MULTIPLY			=GLFW_KEY_KP_MULTIPLY,
        Key_KP_SUBTRACT			=GLFW_KEY_KP_SUBTRACT,
        Key_KP_ADD				=GLFW_KEY_KP_ADD,
        Key_KP_ENTER			=GLFW_KEY_KP_ENTER,
 		Key_KP_EQUAL			=GLFW_KEY_KP_EQUAL,
        
        Key_LSHIFT				=GLFW_KEY_LEFT_SHIFT,  
        Key_LCTRL				=GLFW_KEY_LEFT_CONTROL,	
        Key_LALT				=GLFW_KEY_LEFT_ALT,
        Key_RSHIFT				=GLFW_KEY_RIGHT_SHIFT,
        Key_RCTRL				=GLFW_KEY_RIGHT_CONTROL,
        Key_RALT				=GLFW_KEY_RIGHT_ALT,
    };
	/*
    enum Key
    {
        PHK_A					='A',
        PHK_B					='B',
        PHK_C					='C',
        PHK_D					='D',
        PHK_E					='E',
        PHK_F					='F',
        PHK_G					='G',
        PHK_H					='H',
        PHK_I					='I',
        PHK_J					='J',
        PHK_K					='K',
        PHK_L					='L',
        PHK_M					='M',
        PHK_N					='N',
        PHK_O					='O',
        PHK_P					='P',
        PHK_Q					='Q',
        PHK_R					='R',
        PHK_S					='S',
        PHK_T					='T',
        PHK_U					='U',
        PHK_V					='V',
        PHK_W					='W',
        PHK_X					='X',
        PHK_Y					='Y',
        PHK_Z					='Z',
        PHK_0					='0',
        PHK_1					='1',
        PHK_2					='2',
        PHK_3					='3',
        PHK_4					='4',
        PHK_5					='5',
        PHK_6					='6',
        PHK_7					='7',
        PHK_8					='8',
        PHK_9					='9',
        PHK_BACKTICK            ='`',
		PHK_TILDE				='~',
		PHK_BANG				='!',
        PHK_RIGHTBRACKET        ='[',
        PHK_LEFTBRACKET         =']',
        PHK_SEMICOLON           =';',
        PHK_QUOTE               ='\'',
        PHK_BACKSLASH           ='\\',
		PHK_PIPE				='|',
        PHK_EQUAL               ='=',
		PHK_PLUS				='+',
        PHK_MINUS               ='-',
        PHK_SPACE				=32,
        PHK_ESC					=257,
        PHK_F1					=258,
        PHK_F2					=259,
        PHK_F3					=260,
        PHK_F4					=261,
        PHK_F5					=262,
        PHK_F6					=263,
        PHK_F7					=264,
        PHK_F8					=265,
        PHK_F9					=266,
        PHK_F10					=267,
        PHK_F11					=268,
        PHK_F12					=269,
        PHK_F13					=270,
        PHK_F14					=271,
        PHK_F15					=272,
        PHK_F16					=273,
        PHK_F17					=274,
        PHK_F18					=275,
        PHK_F19					=276,
        PHK_F20					=277,
        PHK_F21					=278,
        PHK_F22					=279,
        PHK_F23					=280,
        PHK_F24					=281,
        PHK_F25					=282,
        PHK_UP					=283,
        PHK_DOWN				=284,
        PHK_LEFT				=285,
        PHK_RIGHT				=286,
        PHK_LSHIFT				=287,
        PHK_RSHIFT				=288,
        PHK_LCTRL				=289,
        PHK_RCTRL				=290,
        PHK_LALT				=291,
        PHK_RALT				=292,
        PHK_TAB					=293,
        PHK_ENTER				=294,
        PHK_BACKSPACE			=295,
        PHK_INSERT				=296,
        PHK_DEL					=297,
        PHK_PAGEUP				=298,
        PHK_PAGEDOWN			=299,
        PHK_HOME				=300,
        PHK_END					=301,
        PHK_KP_0				=302,
        PHK_KP_1				=303,
        PHK_KP_2				=304,
        PHK_KP_3				=305,
        PHK_KP_4				=306,
        PHK_KP_5				=307,
        PHK_KP_6				=308,
        PHK_KP_7				=309,
        PHK_KP_8				=310,
        PHK_KP_9				=311,
        PHK_KP_ADD				=315,
        PHK_KP_SUBTRACT			=314,
        PHK_KP_DIVIDE			=312,
        PHK_KP_MULTIPLY			=313,
        PHK_KP_DECIMAL			=316,
        PHK_KP_EQUAL			=317,
        PHK_KP_ENTER			=318,
        PHK_a					='a',
        PHK_b					='b',
        PHK_c					='c',
        PHK_d					='d',
        PHK_e					='e',
        PHK_f					='f',
        PHK_g					='g',
        PHK_h					='h',
        PHK_i					='i',
        PHK_j					='j',
        PHK_k					='k',
        PHK_l					='l',
        PHK_m					='m',
        PHK_n					='n',
        PHK_o					='o',
        PHK_p					='p',
        PHK_q					='q',
        PHK_r					='r',
        PHK_s					='s',
        PHK_t					='t',
        PHK_u					='u',
        PHK_v					='v',
        PHK_w					='w',
        PHK_x					='x',
        PHK_y					='y',
        PHK_z					='z',
 
    };
	*/
} //namespace phoenix

#endif //__PHOENIXKEYS__
